// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYswNChC78TJsKtSPd9rmCB9l7N04b1Lw',
    appId: '1:88858501133:web:03fca5cc2009e81c763544',
    messagingSenderId: '88858501133',
    projectId: 'uniride-v2',
    authDomain: 'uniride-v2.firebaseapp.com',
    storageBucket: 'uniride-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDyj4mbqIfRviq_2n4vV9J-Tl70055pU',
    appId: '1:88858501133:android:37aedeb287c1e022763544',
    messagingSenderId: '88858501133',
    projectId: 'uniride-v2',
    storageBucket: 'uniride-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4a_K7nTQN3cjAeaU5oxIj9rzmuGh0o5A',
    appId: '1:88858501133:ios:5047d2630af75a9f763544',
    messagingSenderId: '88858501133',
    projectId: 'uniride-v2',
    storageBucket: 'uniride-v2.firebasestorage.app',
    iosBundleId: 'app.uniride.unirideApp',
  );
}
